chore(ci): some debugging

diff --git a/.github/workflows/pr-commitlint.yml b/.github/workflows/pr-commitlint.yml
--- a/.github/workflows/pr-commitlint.yml
+++ b/.github/workflows/pr-commitlint.yml
@@ -38,9 +38,14 @@ jobs:
         run: |
           MESSAGE="${{ github.event.comment.body }}"
           MESSAGE="${MESSAGE#SQUASH COMMIT: }"
-          echo "No commit message proposal found."
-          echo "::set-output name=message::$MESSAGE"
+          if [ -z "$MESSAGE" ]; then
+           echo "No commit message proposal found."
+           echo "::set-output name=message::"
+           exit 1 # This will fail the job if no message is extracted
+          else
+            echo "::set-output name=message::$MESSAGE"
+          fi
 
       - name: Run commitlint
         if: steps.extract-message.outputs.message != ''
-        run: echo "${{steps.commit-message.outputs.message}}" | pnpx commitlint
+        run: echo "${{steps.extract-message.outputs.message}}" | pnpx commitlint
